// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEr0fuAojv2RLq0Z2yuYAz7s0OOTAozoY',
    appId: '1:647587856396:web:3866913dabd78f3d12ae29',
    messagingSenderId: '647587856396',
    projectId: 'imutheboy-b4822',
    authDomain: 'imutheboy-b4822.firebaseapp.com',
    storageBucket: 'imutheboy-b4822.firebasestorage.app',
    measurementId: 'G-G4GKCGME4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBEWok8Wzc922a_KARTlWXlgDKB2qcwVM',
    appId: '1:647587856396:android:07faac5b2623b42412ae29',
    messagingSenderId: '647587856396',
    projectId: 'imutheboy-b4822',
    storageBucket: 'imutheboy-b4822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg0Xq1Q-6bk5rVvLnY2PD087gPpTdmGxY',
    appId: '1:647587856396:ios:27e00922d5e64cbe12ae29',
    messagingSenderId: '647587856396',
    projectId: 'imutheboy-b4822',
    storageBucket: 'imutheboy-b4822.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg0Xq1Q-6bk5rVvLnY2PD087gPpTdmGxY',
    appId: '1:647587856396:ios:27e00922d5e64cbe12ae29',
    messagingSenderId: '647587856396',
    projectId: 'imutheboy-b4822',
    storageBucket: 'imutheboy-b4822.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkhFhXDaqRa6bzGYKIWy0nBKw-PRxnF7I',
    appId: '1:647587856396:web:9c761c21889f805b12ae29',
    messagingSenderId: '647587856396',
    projectId: 'imutheboy-b4822',
    authDomain: 'imutheboy-b4822.firebaseapp.com',
    storageBucket: 'imutheboy-b4822.firebasestorage.app',
    measurementId: 'G-K3GT8S5JQC',
  );
}
